Домашняя работа 2
serge0699/verif_elective_miet pull request #10
Opened 2024-05-27 21:11 UTC by Maksimka81

2024-05-27 21:13 UTC, Maksimka81 commented
** Error: Error at time 35: expected out[0] = 0, got x
#    Time: 35 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 35: expected out[1] = 0, got x
#    Time: 35 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 35: expected out[2] = 1, got x
#    Time: 35 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 35: expected out[3] = 0, got x
#    Time: 35 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 45: expected out[1] = 1, got 0
#    Time: 45 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 45: expected out[2] = 0, got 1
#    Time: 45 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 45: expected out[3] = 0, got 1
#    Time: 45 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 55: expected out[0] = 1, got 0
#    Time: 55 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 55: expected out[1] = 1, got 0
#    Time: 55 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 55: expected out[2] = 0, got 1
#    Time: 55 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 65: expected out[0] = 1, got 0
#    Time: 65 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 65: expected out[1] = 0, got 1
#    Time: 65 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 65: expected out[2] = 0, got 1
#    Time: 65 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 75: expected out[1] = 0, got 1
#    Time: 75 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Error: Error at time 75: expected out[2] = 0, got 1
#    Time: 75 ns  Scope: testbench File: 05_router/testbench.sv Line: 112
# ** Note: $stop    : 05_router/testbench.sv(68)

2024-05-30 12:49 UTC, serge0699 requested changes
Из того, что ты скопировал лог ошибок, я ничего не понял) Да где-то ошибки. Но локализованы ли баги? То есть можешь ли ты мне указать, где они и в чем заключаются? Хотя бы примерно.

2024-05-30 12:49 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        sel = 4'b00_01_10_11;
При взаимодействии с последовательностной логикой используй `<=`.

2024-05-30 12:49 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        sel = 4'b11_10_01_00;
Каким образом выбирал входные значения?) Почему бы не перебрать все возможные. Из всего-то 32 * 32 * 4 = 4096.

2024-06-21 21:52 UTC, serge0699 commented
ДЗ 2 будет разбираться завтра на занятии. Прикреплю эталонную реализацию сюда после разбора.

2024-07-13 20:43 UTC, serge0699 commented
Закрываю PR по сроку давности.

2024-07-13 20:43 UTC, closed without merging