Homework #2
serge0699/verif_elective_miet pull request #11
Opened 2024-05-29 13:32 UTC by Shuregg

Доброй день, Сергей! Домашнее задание с роутером [выполнил ](https://github.com/Shuregg/verif_elective_miet/blob/main/lesson_2/tasks/05_router/testbench.sv), но так и не смог чётко сформулировать в чём заключается ошибка. Заметил, что out[0] и out[3] нередко зануляются, однако закономерность не нашёл.  Подскажи, пожалуйста, в каком направлении копать, всё-таки хочется довести дело до конца.

2024-05-30 12:44 UTC, serge0699 requested changes

2024-05-30 12:44 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +                $warning("(%0t) The correctness of routing is unknown: in[3:0] = %0d.",
Интересно придумал. Тут действительно нельзя точно сказать. Но можно точно сказать, что если хоть где-то 0 иои 1 соответственно, то это ошибка. Можно сделать проверку такую простую и заюзать `continue` (предварительно сохранив текущий пакет в предыдущий), чтобы сразу перейти к след. итерации.

2024-05-30 12:44 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +    function void show_stat();
Отдельный респект за вывод статистики.

2024-05-30 12:44 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +            in  <= $urandom();
Вообще есть общее замечание. Ты рандомишь значения. Окей. А сколько всего возможных комбинаций. 32 * 32 *4 = 4096. Мы за ~4096 тактов можем прогнать. Все возможные комбинации `sel` и `in`.

2024-05-30 12:44 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +            std::randomize(tmp) with { unique{ tmp[0], tmp[1], tmp[2], tmp[3] }; };
А здесь уже более конкретно. Рандомизируя таким образом `sel`, ты не проверяешь конфликты.

Выдержка из спеки:

```
Возникает нюанс с приоретизацией. Если ~sel[n]~ и ~sel[m]~ равны одинаковому номеру выхода,
то на сответствующий выход отправляется вход с меньшим номером. То есть, если n > m, то на
выход попадет ~in[m]~, иначе ~in[n]~. Также, если ни один из входов не назначен выходу, то на
выход отправляется 0.
```

Получаются достаточно "кастрированные" тестовые воздействия.

2024-05-30 12:44 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
>  endmodule
Так, рекомендации выше тебе точно помогут. Также могу еще сказать, что стоит сделать несколько "захардкоженных" сненариев. Это называется направленные тесты (directed test). Например, где на какой-то выход никогда ничего не подается. Или все подаются только на 1. Баги есть в `out[0]`, `out[2]` и `out[3]`.

2024-06-09 09:43 UTC, Shuregg commented
Добрый день, Сергей! Отправил имплементацию констреинтов для классов.

2024-06-21 21:53 UTC, serge0699 commented
Такс, ДЗ с роутером разберу завтра на занятии. Прикреплю сюда эталонную реализацию после разбора.

2024-06-21 22:36 UTC, serge0699 requested changes

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +        // s_tready <= 0;
О, классика, присвоение в выход модуля. Я пару раз тоже так делал:) Молодец, что увидел и поправил.

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +    initial begin
Сильно.

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +    function compare_packets(
Если не объявлять тип возвращаемого аргумента, то функция будет `void`. Так что `return 0` не вернет ничего)

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +    function show_comparison_info(
Тоже будет `void`.

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +                    default: begin
Я подозреваю, что `id` не может быть больше 3, т.к. разрядность ограничена. Но, даже если бы не была ограничена, то ты бы достаточно быстро словил `fatal`. Как думаешь почему? (посмотри на свою генерацию пакетов).

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +                    default: begin
Ты тут перестраховываешься, проверяя сам себя. Ведь ты же и генерируешь значение `tdata_mismatch`. Это неплохая практика, скажу только, что в реальных проектах на это редко есть время. Еще скажу одну опасность такой штуки. Ты начинаешь больше проверять самого себя, чем сам дизайн) В общем можно так делать, но осторожно.

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +            out_mbx.get(pkt_result);
А вот тут архитектурная ошибка. Я просто намекну.

`s_tid  `: `0` `1` `1`
`s_tdata`: `2` `3` `3`
 `m_tid  `: ` ` ` ` ` ` `1`
 `m_tdata`: ` ` ` ` ` ` `0`
 
 Такая работа модуля корректна. Но ты возьмешь `s_tid` `0` и `1` потом возьмешь `m_tid` `1`, пропустишь проверку, т.к. `s_tid` не совпадают и довольный будешь ждать следующего пакета. А пакет с `m_tid` `1` вообще должен был принадлежать двум подряд идущим пакетам с `m_tid` равными `1`.

2024-06-21 22:36 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +endmodule
Вообще мне понравилось. Очень аккуратно и качественно (для того, как ты это понимал) написано. Но есть над чем работать.

2024-06-30 17:28 UTC, Shuregg commented on lesson_3/tasks/06_alu/testbench.sv
> +    initial begin
))

2024-06-30 17:29 UTC, Shuregg commented on lesson_3/tasks/06_alu/testbench.sv
> +    function compare_packets(
Благодарю, исправил

2024-06-30 17:30 UTC, Shuregg commented on lesson_3/tasks/06_alu/testbench.sv
> +                    default: begin
Задал ограничение на диапазон рандомизации id (от 0 до 3)

2024-07-13 20:43 UTC, serge0699 commented
Закрываю PR по сроку давности.

2024-07-13 20:43 UTC, closed without merging