Домашнее задание 1 и 2
serge0699/verif_elective_miet pull request #12
Opened 2024-05-29 14:30 UTC by Bulan0v

2024-05-30 12:56 UTC, serge0699 requested changes

2024-05-30 12:56 UTC, serge0699 commented on lesson_1/tasks/02_truth_table/testbench.sv
> +     initial begin
Тут вопросов нет.

2024-05-30 12:56 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +	bin = 6'b1;
Почему начинаешь с 1? А не с 0.

2024-05-30 12:56 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +            if(onehot_tb !== onehot)begin
В итоге, есть ли ошибки в модуле?

2024-05-30 12:56 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +		    	sel[i] = $urandom_range(0, 3);        // От 0 до 3
Используем `<=`.

2024-05-30 12:56 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        repeat(20) begin
Смотри, ты здесь рандомишь значения. Но на самом-то деле, комбинаций не так много. 32 * 32 * 4 = 4096. Можно просто в цикле перебрать.

2024-05-30 12:56 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        for(int i = 0; i<4; i++) begin
К проверке в целом у меня вопросов нет. Хорошо сделано. Только при сравнении `in` и `out` используй `!==`. Почему? [Ответ](https://stackoverflow.com/questions/5927615/what-is-the-difference-between-and-in-verilog)

2024-05-30 12:56 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        end
Нашлись ли в итоге баги?

2024-05-30 13:43 UTC, Bulan0v commented on lesson_1/tasks/04_onehot/testbench.sv
> +            if(onehot_tb !== onehot)begin
Да
# ** Error: BAD
#    Time: 124 ns  Scope: testbench File: 04_onehot/testbench.sv Line: 56
# bin = 63 onehot: 0000000000000000  onehot_tb: 8000000000000000

2024-05-30 13:46 UTC, Bulan0v commented on lesson_1/tasks/04_onehot/testbench.sv
> +	bin = 6'b1;
Исправил

2024-05-30 18:56 UTC, Bulan0v commented on lesson_2/tasks/05_router/testbench.sv
> +        repeat(20) begin
Переделал

2024-05-30 18:57 UTC, Bulan0v commented on lesson_2/tasks/05_router/testbench.sv
> +        end
Закономерность их не совсем понятно, но что удалось выяснить:
1) аут(2) по дефолту возвращает 1
это мы видим 
# ITERATION =    0
# pkt_prev.sel = 0 0 0 0
# pkt_prev.in = 0000
# pkt_cur.out = 0100
2) сел(0) не записывает 1 в 0
 ITERATION =    1
# pkt_prev.sel = 0 0 0 0
# pkt_prev.in = 0001
# pkt_cur.out = 0100
3) ин(3) записывается в аут(0) без очереди
# ITERATION =    8
# pkt_prev.sel = 0 0 0 0
# pkt_prev.in = 1000
# pkt_cur.out = 0101
но 
# ITERATION =   24
# pkt_prev.sel = 0 0 0 1
# pkt_prev.in = 1000
# pkt_cur.out = 0100
4) сел(1) не записывает 1 в 0
# ITERATION =   18
# pkt_prev.sel = 0 0 0 1
# pkt_prev.in = 0010
# pkt_cur.out = 0100
5) когда сел(0) не равен 0, то ин(2) пишет в 0
# ITERATION =   20
# pkt_prev.sel = 0 0 0 1
# pkt_prev.in = 0100
# pkt_cur.out = 0101
подтверждение 
# ITERATION =   36
# pkt_prev.sel = 0 0 0 2
# pkt_prev.in = 0100
# pkt_cur.out = 0001
6) аномалия с ин(3)
# ITERATION =   40
# pkt_prev.sel = 0 0 0 2
# pkt_prev.in = 1000
# pkt_cur.out = 1000
но
# ITERATION =   56
# pkt_prev.sel = 0 0 0 3
# pkt_prev.in = 1000
# pkt_cur.out = 0100
7) ин(1) не пишется в аут(3)
# ITERATION =   49
# pkt_prev.sel = 0 0 0 3
# pkt_prev.in = 0001
# pkt_cur.out = 0100

2024-06-21 22:37 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        end
Завтра сделаю разбор на это ДЗ.

2024-06-22 08:51 UTC, serge0699 requested changes

2024-06-22 08:51 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +            if(pre_in_p.tid === in_p.tid) begin
Не совсем понял этого мува. При самой первой итерации этого цикла ты сравниваешь с пакетом, который еще не получил даже) Тут можно попроще было сделать:

```SystemVerilog
in_mbx.get(pre_in_p);
forever begin
  in_mbx.get(in_p);
  if(in_p.tid === pre_in_p.tid) begin
    out_mbx.get(out_p);
    // проверка
  end
  pre_in_p = in_p;
end
```

2024-06-22 08:51 UTC, serge0699 commented on lesson_3/tasks/06_alu/testbench.sv
> +endmodule
Остальное принимается.

2024-06-23 21:45 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +        end
```SystemVerilog
module testbench;

    // Тактовый сигнал и сигнал сброса
    logic clk;
    logic aresetn;

    // Остальные сигналы
    logic  [3:0][1:0] sel;
    logic       [3:0] in;
    logic       [3:0] out;

    // Output access indicator
    bit         [3:0] vld;

    router DUT(
        .clk     ( clk     ),
        .aresetn ( aresetn ),
        .sel     ( sel     ),
        .in      ( in      ),
        .out     ( out     )
    );

    // TODO:
    // Найдите все ошибки в модуле ~router~

    // TODO:
    // Определите период тактового сигнала
    parameter CLK_PERIOD = 10;

    // TODO:
    // Cгенерируйте тактовый сигнал
    initial begin
        clk <= 0;
        forever begin
            #(CLK_PERIOD/2) clk <= ~clk;
        end
    end

    // TODO:
    // Cгенерируйте сигнал сброса
    initial begin
        aresetn <= 0;
        #(CLK_PERIOD);
        aresetn <= 1;
    end

    // TODO:
    // Сгенерируйте входные сигналы
    // Не забудьте про ожидание сигнала сброса!
    initial begin
        wait(!aresetn);
        sel <= '0;
        in  <= '0;
        wait(aresetn);
        for(int i = 0; i < 256; i = i + 1) begin
            @(posedge clk);
            sel <= i;
            for(int j = 0; j < 32; j = j + 1) begin
                in <= j;
                @(posedge clk);
            end
        end
        @(posedge clk);
        $stop();
    end

    // Пользуйтесь этой структурой
    typedef struct {
        logic  [3:0][1:0] sel;
        logic       [3:0] in;
        logic       [3:0] out;
    } packet;

    mailbox#(packet) mon2chk = new();

    // TODO:
    // Сохраняйте сигналы каждый положительный
    // фронт тактового сигнала

    initial begin
        packet pkt;
        wait(aresetn);
        forever begin
            @(posedge clk);
            // Пишите здесь.
            pkt.sel = sel;
            pkt.in  = in;
            pkt.out = out;
            mon2chk.put(pkt);
        end
    end

    // TODO:
    // Выполните проверку выходных сигналов
    initial begin
        packet pkt_prev, pkt_cur;
        wait(aresetn);
        mon2chk.get(pkt_prev);
        forever begin
            mon2chk.get(pkt_cur);

            // Пишите здесь
            for(int i = 0; i < 4; i = i + 1) begin
              for(int j = 0; j < 4; j = j + 1) begin
                if( pkt_prev.sel[j] == i ) begin
                  vld[i] = 1;
                  if( pkt_cur.out[i] !== pkt_prev.in[j] )
                      $error("Invalid routing at out[%0d]: \
                        Must be in[%0d] = %1b", i, j, pkt_prev.in[j]);
                  break;
                end
              end
            end
            foreach(vld[i]) begin
                if( !vld[i] && (out[i] !== 0) ) begin
                    $error("Invalid routing at out[%0d]: \
                        Must be default (0)", i);
                end
            end
            vld = '0;
            pkt_prev = pkt_cur;
        end
    end

endmodule
```

2024-07-13 20:42 UTC, serge0699 commented
Закрываю PR по сроку давности.

2024-07-13 20:42 UTC, closed without merging