Домашнее задание 1
serge0699/verif_elective_miet pull request #4
Opened 2024-05-05 19:57 UTC by Maksimka81

2024-05-06 09:10 UTC, serge0699 requested changes

2024-05-06 09:10 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +                     bin, exp_onehot, onehot, (onehot == exp_onehot) ? "Correct" : "Uncorrect");
Лучше для сравнения использовать `===`. Почему? [Ответ](https://stackoverflow.com/questions/5927615/what-is-the-difference-between-and-in-verilog).

2024-05-06 09:10 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +                     bin, exp_onehot, onehot, (onehot == exp_onehot) ? "Correct" : "Uncorrect");
А так все хорошо, кроме `==`. Скажи, нашел ли какие-то баги?

2024-05-06 09:10 UTC, serge0699 commented on lesson_1/tasks/02_truth_table/testbench.sv
> +       initial begin
Гуд. Есть ли какие-то баги в модуле?

2024-05-09 16:15 UTC, Maksimka81 commented
Баги: 
// Референсная таблица истинности модуля 'truth_table':
#    BAD, a b c | _r r
#      0 1 1 | 0 1
# BAD, a b c | _r r
#      1 1 1 | 0 1

// Тестируемый модуль: one-hot кодировщик
 # Input: 63, Expected onehot: 1000000000000000000000000000000000000000000000000000000000000000, Actual onehot: 0000000000000000000000000000000000000000000000000000000000000000, Correct: Uncorrect

2024-05-09 22:15 UTC, serge0699 commented
Принято, молодец!

2024-05-09 22:15 UTC, closed without merging