Домашнее задание 1
serge0699/verif_elective_miet pull request #8
Opened 2024-05-11 10:30 UTC by vladimirkuzia

2024-05-13 10:20 UTC, serge0699 reviewed
Молодец, но нужны доработки. Ожидаю.

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/02_truth_table/testbench.sv
> +                $error("incorrect truth_table");
Здесь я бы рекомендовал объединить вывод в одиночный вызов `$error`:

```verilog
$error({"Incorrect truth_table:\n",
    "a:%b, b:%b, c:%b, r:%b _r:%b"}, a, b, c,, r, _r);
```

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/02_truth_table/testbench.sv
> +            if( _r != r ) begin
Лучше использовать `!==` вместо `!=` при сравнении типов с 4 состояниями (0, 1, x, z). `logic` как раз такой тип. Почему? [Ответ](https://stackoverflow.com/a/5929076).

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +        bin = 1; #1ns;
Почему стартуешь с 1, а не с нуля?) Его же тоже нужно проверить.

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +                range = range + 1;
Я так понял, что переменная `range` указывает на позицию 1. Но для чего она тебе я так и не понял.

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +            $display("bin = ",bin ," range = ", range," onehot: %d ", onehot);
Смотри, ты просто делаешь `$display`. А где сама проверка? Твой код должен содержать что-то вроде:

```verilog
    logic onehot_ref;
    onehot_ref =// считаем эталонное значение
    if(onehot_ref !== onehot) $error( // тут текст сообщения об ошибки
```

2024-05-13 10:20 UTC, serge0699 commented on lesson_1/tasks/04_onehot/testbench.sv
> +                break;
При использовании `break` ты сразу вываливаешься из этого цикла. Ты буквально выполняешь его только один раз для i = 0. Но зачем?) Просто напиши:

```verilog
    bin = bin + 1; $1ns;
    range = 1;
```

Правда я все еще не понимаю, зачем тебе переменная `range`.

2024-06-03 07:59 UTC, vladimirkuzia commented on lesson_1/tasks/02_truth_table/testbench.sv
> +                $error("incorrect truth_table");
написал

2024-06-03 08:01 UTC, vladimirkuzia commented on lesson_1/tasks/02_truth_table/testbench.sv
> +            if( _r != r ) begin
да, я понял про доп проверку на z и x, если с двух сторон x , то получу true, аналогично с z

2024-06-03 08:01 UTC, vladimirkuzia commented on lesson_1/tasks/04_onehot/testbench.sv
> +        bin = 1; #1ns;
исправил

2024-06-03 08:04 UTC, vladimirkuzia commented on lesson_1/tasks/04_onehot/testbench.sv
> +                range = range + 1;
range это просто разрядность, он же bin, но считается через выход, зачем? Не знаю, авторская бесполезная изюминка, захотелось проверить в обратную сторону.

2024-06-03 08:04 UTC, vladimirkuzia commented on lesson_1/tasks/04_onehot/testbench.sv
> +            $display("bin = ",bin ," range = ", range," onehot: %d ", onehot);
добавил

2024-06-03 08:04 UTC, vladimirkuzia commented on lesson_1/tasks/04_onehot/testbench.sv
> +                break;
да, увидел, спасибо

2024-06-05 06:51 UTC, vladimirkuzia commented
залил второе дз, если я правильно понял трактовку задания и правильно написал реф модель, то понятия не имею, в чём там проблема, все выходы бьются ошибками))))

2024-06-05 08:45 UTC, vladimirkuzia commented
Исправил косяк с посылками

2024-06-21 19:37 UTC, serge0699 commented
Первое ДЗ засчитано. Сейчас смотрю второе.

2024-06-23 21:43 UTC, serge0699 requested changes

2024-06-23 21:43 UTC, serge0699 commented on lesson_2/tasks/05_router/testbench.sv
> +            for(int i = 0; i <= 3; i++ ) begin
```SystemVerilog
module testbench;

    // Тактовый сигнал и сигнал сброса
    logic clk;
    logic aresetn;

    // Остальные сигналы
    logic  [3:0][1:0] sel;
    logic       [3:0] in;
    logic       [3:0] out;

    // Output access indicator
    bit         [3:0] vld;

    router DUT(
        .clk     ( clk     ),
        .aresetn ( aresetn ),
        .sel     ( sel     ),
        .in      ( in      ),
        .out     ( out     )
    );

    // TODO:
    // Найдите все ошибки в модуле ~router~

    // TODO:
    // Определите период тактового сигнала
    parameter CLK_PERIOD = 10;

    // TODO:
    // Cгенерируйте тактовый сигнал
    initial begin
        clk <= 0;
        forever begin
            #(CLK_PERIOD/2) clk <= ~clk;
        end
    end

    // TODO:
    // Cгенерируйте сигнал сброса
    initial begin
        aresetn <= 0;
        #(CLK_PERIOD);
        aresetn <= 1;
    end

    // TODO:
    // Сгенерируйте входные сигналы
    // Не забудьте про ожидание сигнала сброса!
    initial begin
        wait(!aresetn);
        sel <= '0;
        in  <= '0;
        wait(aresetn);
        for(int i = 0; i < 256; i = i + 1) begin
            @(posedge clk);
            sel <= i;
            for(int j = 0; j < 32; j = j + 1) begin
                in <= j;
                @(posedge clk);
            end
        end
        @(posedge clk);
        $stop();
    end

    // Пользуйтесь этой структурой
    typedef struct {
        logic  [3:0][1:0] sel;
        logic       [3:0] in;
        logic       [3:0] out;
    } packet;

    mailbox#(packet) mon2chk = new();

    // TODO:
    // Сохраняйте сигналы каждый положительный
    // фронт тактового сигнала

    initial begin
        packet pkt;
        wait(aresetn);
        forever begin
            @(posedge clk);
            // Пишите здесь.
            pkt.sel = sel;
            pkt.in  = in;
            pkt.out = out;
            mon2chk.put(pkt);
        end
    end

    // TODO:
    // Выполните проверку выходных сигналов
    initial begin
        packet pkt_prev, pkt_cur;
        wait(aresetn);
        mon2chk.get(pkt_prev);
        forever begin
            mon2chk.get(pkt_cur);

            // Пишите здесь
            for(int i = 0; i < 4; i = i + 1) begin
              for(int j = 0; j < 4; j = j + 1) begin
                if( pkt_prev.sel[j] == i ) begin
                  vld[i] = 1;
                  if( pkt_cur.out[i] !== pkt_prev.in[j] )
                      $error("Invalid routing at out[%0d]: \
                        Must be in[%0d] = %1b", i, j, pkt_prev.in[j]);
                  break;
                end
              end
            end
            foreach(vld[i]) begin
                if( !vld[i] && (out[i] !== 0) ) begin
                    $error("Invalid routing at out[%0d]: \
                        Must be default (0)", i);
                end
            end
            vld = '0;
            pkt_prev = pkt_cur;
        end
    end

endmodule
```

2024-07-13 20:44 UTC, serge0699 commented
Закрываю PR по сроку давности.

2024-07-13 20:44 UTC, closed without merging